namespace Microsoft.UI.Xaml.Controls;

public enum Symbol
{
    Previous = 57600,
    Next,
    Play,
    Pause,
    Edit,
    Save,
    Clear,
    Delete,
    Remove,
    Add,
    Cancel,
    Accept,
    More,
    Redo,
    Undo,
    Home,
    Up,
    Forward,
    Back,
    Favorite,
    Camera,
    Setting,
    Video,
    Sync,
    Download,
    Mail,
    Find,
    Help,
    Upload,
    Emoji,
    TwoPage,
    LeaveChat,
    MailForward,
    Clock,
    Send,
    Crop,
    RotateCamera,
    People,
    OpenPane,
    ClosePane,
    World,
    Flag,
    PreviewLink,
    Globe,
    Trim,
    AttachCamera,
    ZoomIn,
    Bookmarks,
    Document,
    ProtectedDocument,
    Page,
    Bullets,
    Comment,
    MailFilled,
    ContactInfo,
    HangUp,
    ViewAll,
    MapPin,
    Phone,
    VideoChat,
    Switch,
    Contact,
    Rename,
    Pin = 57665,
    MusicInfo,
    Go,
    Keyboard,
    DockLeft,
    DockRight,
    DockBottom,
    Remote,
    Refresh,
    Rotate,
    Shuffle,
    List,
    Shop,
    SelectAll,
    Orientation,
    Import,
    ImportAll,
    BrowsePhotos = 57685,
    WebCam,
    Pictures = 57688,
    SaveLocal,
    Caption,
    Stop,
    ShowResults,
    Volume,
    Repair,
    Message,
    Page2,
    CalendarDay,
    CalendarWeek,
    Calendar,
    Character,
    MailReplyAll,
    Read,
    Link,
    Account,
    ShowBcc,
    HideBcc,
    Cut,
    Attach,
    Paste,
    Filter,
    Copy,
    Emoji2,
    Important,
    MailReply,
    SlideShow,
    Sort,
    Manage = 57720,
    AllApps,
    DisconnectDrive,
    MapDrive,
    NewWindow,
    OpenWith,
    ContactPresence = 57729,
    Priority,
    GoToToday = 57732,
    Font,
    FontColor,
    Contact2,
    Folder,
    Audio,
    Placeholder,
    View,
    SetLockScreen,
    SetTile,
    ClosedCaption = 57744,
    StopSlideShow,
    Permissions,
    Highlight,
    DisableUpdates,
    UnFavorite,
    UnPin,
    OpenLocal,
    Mute,
    Italic,
    Underline,
    Bold,
    MoveToFolder,
    LikeDislike,
    Dislike,
    Like,
    AlignRight,
    AlignCenter,
    AlignLeft,
    Zoom,
    ZoomOut,
    OpenFile,
    OtherUser,
    Admin,
    Street = 57795,
    Map,
    ClearSelection,
    FontDecrease,
    FontIncrease,
    FontSize,
    CellPhone,
    ReShare,
    Tag,
    RepeatOne,
    RepeatAll,
    OutlineStar,
    SolidStar,
    Calculator,
    Directions,
    Target,
    Library,
    PhoneBook,
    Memo,
    Microphone,
    PostUpdate,
    BackToWindow,
    FullScreen,
    NewFolder,
    CalendarReply,
    UnSyncFolder = 57821,
    ReportHacked,
    SyncFolder,
    BlockContact,
    SwitchApps,
    AddFriend,
    TouchPointer,
    GoToStart,
    ZeroBars,
    OneBar,
    TwoBars,
    ThreeBars,
    FourBars,
    Scan = 58004,
    Preview,
    GlobalNavigationButton = 59136,
    Share = 59181,
    Print = 59209,
    XboxOneConsole = 59792
}

public sealed class SymbolIcon : IconElement
{
    public static readonly DependencyProperty SymbolProperty = DependencyProperty.Register(
        nameof(Symbol), typeof(Symbol), typeof(SymbolIcon), new PropertyMetadata(Symbol.Emoji));

    public Symbol Symbol
    {
        get => (Symbol)(GetValue(SymbolProperty) ?? Symbol.Emoji);
        set => SetValue(SymbolProperty, value);
    }
}
