#!/usr/bin/env python3
"""Generate Unicode mirroring and vertical-form mappings from pinned HarfBuzz data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_array(source: str, c_type: str, name: str) -> list[int]:
    match = re.search(
        rf"static const {re.escape(c_type)} {re.escape(name)}\[\d+\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {name}")
    return [int(value) for value in re.findall(r"-?\d+", match.group("body"))]


def format_values(values: list[int], per_line: int = 16) -> str:
    return "\n".join(
        "        " + ", ".join(f"0x{value:X}" for value in values[index : index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    ucd_source = (args.harfbuzz_root / "src" / "hb-ucd-table.hh").read_text(encoding="utf-8")
    unicode_source = (args.harfbuzz_root / "src" / "hb-unicode.hh").read_text(encoding="utf-8")
    u8 = parse_array(ucd_source, "uint8_t", "_hb_ucd_u8")
    i16 = parse_array(ucd_source, "int16_t", "_hb_ucd_i16")
    if len(u8) != 19_845 or len(i16) != 196:
        raise RuntimeError(f"Unexpected HarfBuzz UCD data: u8={len(u8)}, i16={len(i16)}")

    def nibble(offset: int, index: int) -> int:
        return (u8[offset + (index >> 1)] >> ((index & 1) << 2)) & 15

    def mirror_delta(code_point: int) -> int:
        if code_point >= 65_380:
            return 0
        level0 = nibble(10_874, code_point >> 8)
        level1 = u8[11_002 + (level0 << 3) + ((code_point >> 5) & 7)]
        level2 = u8[11_118 + (level1 << 3) + ((code_point >> 2) & 7)]
        return i16[level2 + (code_point & 3)]

    mirror_pairs: list[int] = []
    for code_point in range(65_380):
        delta = mirror_delta(code_point)
        if delta:
            mirror_pairs.extend((code_point, code_point + delta))

    vertical_body = re.search(
        r"vertical_char_for\s*\([^)]*\)\s*\{(?P<body>.*?)\n\s*return u;",
        unicode_source,
        re.DOTALL,
    )
    if vertical_body is None:
        raise RuntimeError("Could not find vertical_char_for")
    vertical_pairs: list[int] = []
    for source, target in re.findall(
        r"case\s+0x([0-9a-fA-F]+)u:\s*return\s+0x([0-9a-fA-F]+)u;",
        vertical_body.group("body"),
    ):
        vertical_pairs.extend((int(source, 16), int(target, 16)))

    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ucd-table.hh and hb-unicode.hh, Unicode 17.0.0.
// Regenerate with eng/generate-unicode-directional-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class UnicodeDirectionalData
{{
    private static readonly uint[] s_mirrorPairs =
    [
{format_values(mirror_pairs)}
    ];

    private static readonly uint[] s_verticalPairs =
    [
{format_values(vertical_pairs)}
    ];

    public static uint GetMirroredCodePoint(uint codePoint) => Find(s_mirrorPairs, codePoint);

    public static uint GetVerticalCodePoint(uint codePoint) => Find(s_verticalPairs, codePoint);

    private static uint Find(uint[] pairs, uint codePoint)
    {{
        var low = 0;
        var high = pairs.Length / 2 - 1;
        while (low <= high)
        {{
            int middle = (low + high) >> 1;
            int offset = middle * 2;
            if (codePoint < pairs[offset]) high = middle - 1;
            else if (codePoint > pairs[offset]) low = middle + 1;
            else return pairs[offset + 1];
        }}
        return codePoint;
    }}
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
