#!/usr/bin/env python3
"""Generate the compact Unicode Arabic joining table used by the shaper."""

from __future__ import annotations

import argparse
import pathlib
import re


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_table", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    source = args.harfbuzz_table.read_text(encoding="utf-8")
    match = re.search(
        r"static const uint8_t _hb_arabic_joining_u8\[737\]=\s*\{(?P<body>.*?)\};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise SystemExit("Unable to find HarfBuzz's packed Arabic joining table")

    values = [int(value) for value in re.findall(r"\d+", match.group("body"))]
    if len(values) != 737 or any(value > 255 for value in values):
        raise SystemExit(f"Expected 737 bytes, found {len(values)}")

    rows = []
    for start in range(0, len(values), 16):
        rows.append("        " + ", ".join(str(value) for value in values[start : start + 16]) + ",")

    output = f'''// Generated by eng/generate-arabic-joining-table.py from HarfBuzz's
// Unicode 17.0 ArabicShaping table. Do not edit this file manually.
using System.Globalization;
using System.Text;

namespace ProGPU.Text;

internal static class ArabicJoiningData
{{
    internal enum JoiningType : byte
    {{
        NonJoining = 0,
        LeftJoining = 1,
        RightJoining = 2,
        DualJoining = 3,
        Alaph = 4,
        DalathRish = 5,
        Transparent = 6
    }}

    private static ReadOnlySpan<byte> Packed =>
    [
{chr(10).join(rows)}
    ];

    public static JoiningType GetJoiningType(uint codePoint)
    {{
        byte value = codePoint < 125260 ? LookupPacked(codePoint) : (byte)7;
        if (value != 7)
        {{
            return (JoiningType)value;
        }}

        UnicodeCategory category = Rune.GetUnicodeCategory(new Rune((int)codePoint));
        return category is UnicodeCategory.NonSpacingMark or UnicodeCategory.EnclosingMark or UnicodeCategory.Format
            ? JoiningType.Transparent
            : JoiningType.NonJoining;
    }}

    private static byte LookupPacked(uint codePoint)
    {{
        ReadOnlySpan<byte> data = Packed;
        uint level0 = Nibble(data, codePoint >> 9);
        uint level1 = data[(int)(123 + level0 * 8 + ((codePoint >> 6) & 7))];
        uint level2 = data[(int)(209 + level1 + ((codePoint >> 3) & 7))];
        return Nibble(data[441..], level2 * 8 + (codePoint & 7));
    }}

    private static byte Nibble(ReadOnlySpan<byte> data, uint index) =>
        (byte)((data[(int)(index >> 1)] >> (int)((index & 1) << 2)) & 15);
}}
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
