#!/usr/bin/env python3
"""Generate Unicode 17 Arabic presentation-form fallback tables from HarfBuzz."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_hex_values(text: str) -> list[int]:
    return [int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]+)u?", text)]


def extract_block(source: str, declaration: str) -> str:
    start = source.find(declaration)
    if start < 0:
        raise RuntimeError(f"Could not find {declaration}")
    body_start = source.find("=", start) + 1
    end = source.find("\n};", body_start)
    if body_start == 0 or end < 0:
        raise RuntimeError(f"Could not parse {declaration}")
    return source[body_start:end]


def parse_ligatures(source: str, declaration: str, component_count: int) -> list[int]:
    block = extract_block(source, declaration)
    result: list[int] = []
    set_pattern = re.compile(
        r"\{\s*(0x[0-9A-Fa-f]+u),\s*\{(?P<body>.*?)\}\s*\}\s*,?",
        re.DOTALL,
    )
    row_pattern = re.compile(
        r"\{\s*\{(?P<components>[^}]*)\}\s*,\s*(?P<ligature>0x[0-9A-Fa-f]+u)\s*\}"
    )
    for set_match in set_pattern.finditer(block):
        first = parse_hex_values(set_match.group(1))[0]
        for row in row_pattern.finditer(set_match.group("body")):
            components = parse_hex_values(row.group("components"))
            if len(components) != component_count:
                raise RuntimeError(f"Expected {component_count} components, found {components}")
            ligature = parse_hex_values(row.group("ligature"))[0]
            result.extend((first, *components, ligature))
    return result


def format_values(values: list[int], per_line: int = 16) -> str:
    return "\n".join(
        "        " + ", ".join(f"0x{value:04X}" for value in values[index : index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def parse_pua_map(path: Path) -> list[int]:
    mappings: list[tuple[int, int]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) < 2:
            raise RuntimeError(f"Malformed PUA mapping in {path}: {line}")
        mappings.append((int(fields[1], 16), int(fields[0], 16)))
    mappings.sort()
    return [value for mapping in mappings for value in mapping]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_table", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--pua-simplified", type=Path)
    parser.add_argument("--pua-traditional", type=Path)
    args = parser.parse_args()

    source = args.harfbuzz_table.read_text(encoding="utf-8")
    shaping = parse_hex_values(extract_block(source, "static const uint16_t shaping_table[][4]"))
    if len(shaping) != (0x06D3 - 0x0621 + 1) * 4:
        raise RuntimeError(f"Unexpected shaping table length: {len(shaping)}")
    ligature3 = parse_ligatures(source, "} ligature_3_table[]", 2)
    ligature2 = parse_ligatures(source, "} ligature_table[]", 1)
    mark_ligature2 = parse_ligatures(source, "} ligature_mark_table[]", 1)
    simplified_pua = parse_pua_map(args.pua_simplified) if args.pua_simplified else []
    traditional_pua = parse_pua_map(args.pua_traditional) if args.pua_traditional else []
    if bool(simplified_pua) != bool(traditional_pua):
        raise RuntimeError("Both legacy Arabic PUA mapping files must be provided together")

    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ot-shaper-arabic-table.hh, Unicode 17.0.0.
// Regenerate with eng/generate-arabic-fallback-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class ArabicFallbackData
{{
    public const uint FirstCodePoint = 0x0621;
    public const uint LastCodePoint = 0x06D3;

    public static ReadOnlySpan<ushort> ShapingForms =>
    [
{format_values(shaping)}
    ];

    public static ReadOnlySpan<ushort> ThreeComponentLigatures =>
    [
{format_values(ligature3)}
    ];

    public static ReadOnlySpan<ushort> TwoComponentLigatures =>
    [
{format_values(ligature2)}
    ];

    public static ReadOnlySpan<ushort> MarkLigatures =>
    [
{format_values(mark_ligature2)}
    ];

    public static ReadOnlySpan<ushort> SimplifiedPuaMappings =>
    [
{format_values(simplified_pua)}
    ];

    public static ReadOnlySpan<ushort> TraditionalPuaMappings =>
    [
{format_values(traditional_pua)}
    ];
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
