#!/usr/bin/env python3
"""Generate Unicode 17 canonical-combining-class ranges from pinned HarfBuzz data."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_array(source: str, c_type: str, name: str) -> list[int]:
    match = re.search(
        rf"static const {re.escape(c_type)} {re.escape(name)}\[\d+\]\s*=\s*\{{(?P<body>.*?)\}};",
        source,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(f"Could not find {name}")
    return [int(value) for value in re.findall(r"\d+", match.group("body"))]


def format_values(values: list[int], per_line: int) -> str:
    return "\n".join(
        "        " + ", ".join(str(value) for value in values[index : index + per_line]) + ","
        for index in range(0, len(values), per_line)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("harfbuzz_root", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    source = (args.harfbuzz_root / "src" / "hb-ucd-table.hh").read_text(encoding="utf-8")
    u8 = parse_array(source, "uint8_t", "_hb_ucd_u8")
    if len(u8) != 19_845:
        raise RuntimeError(f"Unexpected HarfBuzz UCD byte table length: {len(u8)}")

    def combining_class(code_point: int) -> int:
        if code_point >= 125_259:
            return 0
        level0 = u8[8294 + (code_point >> 9)]
        level1 = u8[8539 + (level0 << 4) + ((code_point >> 5) & 15)]
        level2 = u8[9270 + (level1 << 3) + ((code_point >> 2) & 7)]
        return u8[10370 + (level2 << 2) + (code_point & 3)]

    ranges: list[int] = []
    code_point = 0
    while code_point < 0x110000:
        value = combining_class(code_point)
        start = code_point
        code_point += 1
        while code_point < 0x110000 and combining_class(code_point) == value:
            code_point += 1
        if value != 0:
            ranges.extend((start, code_point - 1, value))

    generated = f'''// <auto-generated />
// Source: HarfBuzz hb-ucd-table.hh, Unicode 17.0.0.
// Regenerate with eng/generate-unicode-combining-class-table.py and the pinned HarfBuzz source.

namespace ProGPU.Text;

internal static class UnicodeCombiningClassData
{{
    private static readonly uint[] s_ranges =
    [
{format_values(ranges, 18)}
    ];

    public static byte GetCanonicalClass(uint codePoint)
    {{
        var low = 0;
        var high = s_ranges.Length / 3 - 1;
        while (low <= high)
        {{
            int middle = (low + high) >> 1;
            int offset = middle * 3;
            if (codePoint < s_ranges[offset]) high = middle - 1;
            else if (codePoint > s_ranges[offset + 1]) low = middle + 1;
            else return (byte)s_ranges[offset + 2];
        }}
        return 0;
    }}
}}
'''
    args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
